apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mgo-replicaset
  namespace: ns1
spec:
  version: "3.6-v3"
  replicas: 1
  replicaSet:
    name: rs0
  storage:
    storageClassName: "openebs-cstor-disk"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
