version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: "/home/clayton/node"
    environment:
      - NODE_ENV=production
    volumes:
      - /home/clayton/node/
    expose:
      - "3003"
    command: "npm start"

